default: true

# Disabling line length
MD013: false

# Not relevant for a documentation site
MD014: false

# I'm lazy, I don't wanna pad extra lines for these code blocks
MD031: false

# Requiring a language in code blocks (we use them for some text formatting)
MD040: false
